name: Markdown Lint

on:
  pull_request:
    paths:
      - "**/*.md"

permissions:
  contents: read
  pull-requests: write

jobs:
  lint:
    name: Markdown Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        # actions/checkout v6.0.3
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1

      - name: Markdown Lint via composite action
        uses: tomio2480/github-workflows/.github/actions/markdown-lint@558c5440bd4f4d60c26b2ad66cc9020a71c1ebbb # v2.17.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
